"use strict";
var __createBinding = (this && this.__createBinding) || (Object.create ? (function(o, m, k, k2) {
    if (k2 === undefined) k2 = k;
    var desc = Object.getOwnPropertyDescriptor(m, k);
    if (!desc || ("get" in desc ? !m.__esModule : desc.writable || desc.configurable)) {
      desc = { enumerable: true, get: function() { return m[k]; } };
    }
    Object.defineProperty(o, k2, desc);
}) : (function(o, m, k, k2) {
    if (k2 === undefined) k2 = k;
    o[k2] = m[k];
}));
var __setModuleDefault = (this && this.__setModuleDefault) || (Object.create ? (function(o, v) {
    Object.defineProperty(o, "default", { enumerable: true, value: v });
}) : function(o, v) {
    o["default"] = v;
});
var __importStar = (this && this.__importStar) || (function () {
    var ownKeys = function(o) {
        ownKeys = Object.getOwnPropertyNames || function (o) {
            var ar = [];
            for (var k in o) if (Object.prototype.hasOwnProperty.call(o, k)) ar[ar.length] = k;
            return ar;
        };
        return ownKeys(o);
    };
    return function (mod) {
        if (mod && mod.__esModule) return mod;
        var result = {};
        if (mod != null) for (var k = ownKeys(mod), i = 0; i < k.length; i++) if (k[i] !== "default") __createBinding(result, mod, k[i]);
        __setModuleDefault(result, mod);
        return result;
    };
})();
var __importDefault = (this && this.__importDefault) || function (mod) {
    return (mod && mod.__esModule) ? mod : { "default": mod };
};
Object.defineProperty(exports, "__esModule", { value: true });
const node_path_1 = __importDefault(require("node:path"));
const Fs = __importStar(require("node:fs"));
const node_test_1 = require("node:test");
const node_assert_1 = __importDefault(require("node:assert"));
const live_runner_1 = require("../../live-runner");
const live_entity_1 = require("../../live-entity");
const __1 = require("../../..");
const utility_1 = require("../../utility");
(0, utility_1.loadEnvLocal)(__dirname + '/../../../.env.local');
(0, node_test_1.describe)('ListSubscribersResponseDtoEntity', async () => {
    // Per-test live pacing. Delay is read from sdk-test-control.json's
    // `test.live.delayMs`; only sleeps when NOVU_TEST_LIVE=TRUE.
    (0, node_test_1.afterEach)((0, utility_1.liveDelay)('NOVU_TEST_LIVE'));
    (0, node_test_1.test)('instance', async () => {
        const testsdk = __1.NovuSDK.test();
        const ent = testsdk.ListSubscribersResponseDto();
        (0, node_assert_1.default)(null != ent);
    });
    (0, node_test_1.test)('basic', async (t) => {
        const live = 'TRUE' === process.env.NOVU_TEST_LIVE;
        for (const op of ['list']) {
            if (!live && (0, utility_1.maybeSkipControl)(t, 'entityOp', 'list_subscribers_response_dto.' + op, live))
                return;
        }
        const setup = basicSetup();
        if (setup.live) {
            return (0, live_entity_1.runLiveEntity)(setup, { "active": true, "alias": { "field": {} }, "fields": { "avatar": { "a": true, "h": "Avatar", "n": "avatar", "r": false, "sh": "The URL of the subscriber's avatar image.", "t": "`$STRING`", "key$": "avatar", "index$": 0 }, "channels": { "a": true, "h": "Channels", "n": "channels", "r": false, "sh": "An array of channel settings associated with the subscriber.", "t": "`$ARRAY`", "key$": "channels", "index$": 1 }, "createdAt": { "a": true, "h": "Created At", "n": "createdAt", "r": true, "sh": "The timestamp indicating when the subscriber was created, in ISO 8601 format.", "t": "`$STRING`", "key$": "createdAt", "index$": 2 }, "data": { "a": true, "h": "Data", "n": "data", "r": false, "sh": "Additional custom data for the subscriber", "t": "`$OBJECT`", "key$": "data", "index$": 3 }, "deleted": { "a": true, "h": "Deleted", "n": "deleted", "r": true, "sh": "Indicates whether the subscriber has been deleted.", "t": "`$BOOLEAN`", "key$": "deleted", "index$": 4 }, "email": { "a": true, "h": "Email", "n": "email", "r": false, "sh": "The email address of the subscriber.", "t": "`$STRING`", "key$": "email", "index$": 5 }, "environmentId": { "a": true, "h": "Environment Id", "n": "environmentId", "r": true, "sh": "The unique identifier of the environment associated with this subscriber.", "t": "`$STRING`", "key$": "environmentId", "index$": 6 }, "firstName": { "a": true, "h": "First Name", "n": "firstName", "r": false, "sh": "The first name of the subscriber.", "t": "`$STRING`", "key$": "firstName", "index$": 7 }, "id": { "a": true, "h": "Id", "n": "id", "r": false, "sh": "The internal ID generated by Novu for your subscriber.", "t": "`$STRING`", "key$": "id", "index$": 8 }, "isOnline": { "a": true, "h": "Is Online", "n": "isOnline", "r": false, "sh": "Indicates whether the subscriber is currently online.", "t": "`$BOOLEAN`", "key$": "isOnline", "index$": 9 }, "lastName": { "a": true, "h": "Last Name", "n": "lastName", "r": false, "sh": "The last name of the subscriber.", "t": "`$STRING`", "key$": "lastName", "index$": 10 }, "lastOnlineAt": { "a": true, "h": "Last Online At", "n": "lastOnlineAt", "r": false, "sh": "The timestamp indicating when the subscriber was last online, in ISO 8601 format.", "t": "`$STRING`", "key$": "lastOnlineAt", "index$": 11 }, "locale": { "a": true, "h": "Locale", "n": "locale", "r": false, "sh": "The locale setting of the subscriber, indicating their preferred language or region.", "t": "`$STRING`", "key$": "locale", "index$": 12 }, "organizationId": { "a": true, "h": "Organization Id", "n": "organizationId", "r": true, "sh": "The unique identifier of the organization to which the subscriber belongs.", "t": "`$STRING`", "key$": "organizationId", "index$": 13 }, "phone": { "a": true, "h": "Phone", "n": "phone", "r": false, "sh": "The phone number of the subscriber.", "t": "`$STRING`", "key$": "phone", "index$": 14 }, "subscriberId": { "a": true, "h": "Subscriber Id", "n": "subscriberId", "r": true, "sh": "The identifier used to create this subscriber, which typically corresponds to the user ID in your system.", "t": "`$STRING`", "key$": "subscriberId", "index$": 15 }, "timezone": { "a": true, "h": "Timezone", "n": "timezone", "r": false, "sh": "Timezone of the subscriber", "t": "`$STRING`", "key$": "timezone", "index$": 16 }, "topics": { "a": true, "de": true, "h": "Topics", "n": "topics", "r": false, "sh": "An array of topics that the subscriber is subscribed to.", "t": "`$ARRAY`", "key$": "topics", "index$": 17 }, "updatedAt": { "a": true, "h": "Updated At", "n": "updatedAt", "r": true, "sh": "The timestamp indicating when the subscriber was last updated, in ISO 8601 format.", "t": "`$STRING`", "key$": "updatedAt", "index$": 18 }, "v": { "a": true, "h": "V", "n": "v", "r": false, "sh": "The version of the subscriber document.", "t": "`$NUMBER`", "key$": "v", "index$": 19 } }, "id": { "field": "id", "name": "id" }, "name": "list_subscribers_response_dto", "op": { "list": { "input": "data", "name": "list", "points": [{ "a": true, "co": { "id": "GET /v2/subscribers", "source": "openapi3", "version": 2 }, "g": { "header": [{ "a": true, "k": "header", "n": "idempotency_key", "or": "idempotency_key", "r": false, "t": "`$STRING`", "index$": 0 }], "query": [{ "a": true, "k": "query", "n": "after", "or": "after", "r": false, "t": "`$STRING`", "index$": 0 }, { "a": true, "k": "query", "n": "before", "or": "before", "r": false, "t": "`$STRING`", "index$": 1 }, { "a": true, "k": "query", "n": "email", "or": "email", "r": false, "t": "`$STRING`", "index$": 2 }, { "a": true, "k": "query", "n": "include_cursor", "or": "include_cursor", "r": false, "t": "`$BOOLEAN`", "index$": 3 }, { "a": true, "ex": 10, "k": "query", "n": "limit", "or": "limit", "r": false, "t": "`$NUMBER`", "index$": 4 }, { "a": true, "k": "query", "n": "name", "or": "name", "r": false, "t": "`$STRING`", "index$": 5 }, { "a": true, "k": "query", "n": "order_by", "or": "order_by", "r": false, "t": "`$STRING`", "index$": 6 }, { "a": true, "k": "query", "n": "order_direction", "or": "order_direction", "r": false, "t": "`$STRING`", "index$": 7 }, { "a": true, "k": "query", "n": "phone", "or": "phone", "r": false, "t": "`$STRING`", "index$": 8 }, { "a": true, "k": "query", "n": "subscriber_id", "or": "subscriber_id", "r": false, "t": "`$STRING`", "index$": 9 }] }, "k": "http", "m": "GET", "o": "/v2/subscribers", "q": { "exist": ["after", "before", "email", "idempotency_key", "include_cursor", "limit", "name", "order_by", "order_direction", "phone", "subscriber_id"] }, "r": {}, "s": [{ "lit": "v2" }, { "lit": "subscribers" }], "t": { "req": "`reqdata`", "res": "`body.data`" }, "index$": 0 }], "key$": "list" } }, "relations": { "ancestors": [] }, "key$": "list_subscribers_response_dto", "name__orig": "list_subscribers_response_dto", "Name": "ListSubscribersResponseDto", "name_": "list_subscribers_response_dto", "name-": "list-subscribers-response-dto", "NAME": "LIST_SUBSCRIBERS_RESPONSE_DTO", "index$": 37 }, { "active": true, "entity": "list_subscribers_response_dto", "key$": "BasicListSubscribersResponseDtoFlow", "kind": "basic", "name": "BasicListSubscribersResponseDtoFlow", "param": {}, "step": [{ "a": true, "d": {}, "i": {}, "m": {}, "o": "list", "s": [], "v": [{ "apply": "ItemExists", "def": { "ref": "list_subscribers_response_dto_ref01" } }], "index$": 0 }] }, 'ListSubscribersResponseDto', { "GET /v2/subscribers": { "protocol": "http", "parameters": [{ "name": "after", "required": false, "in": "query", "description": "Cursor for pagination indicating the starting point after which to fetch results.", "schema": { "type": "string" }, "index$": 0 }, { "name": "before", "required": false, "in": "query", "description": "Cursor for pagination indicating the ending point before which to fetch results.", "schema": { "type": "string" }, "index$": 1 }, { "name": "limit", "required": false, "in": "query", "description": "Limit the number of items to return", "example": 10, "schema": { "type": "number" }, "index$": 2 }, { "name": "orderDirection", "required": false, "in": "query", "description": "Direction of sorting", "schema": { "enum": ["ASC", "DESC"], "type": "string" }, "index$": 3 }, { "name": "orderBy", "required": false, "in": "query", "description": "Field to order by", "schema": { "type": "string" }, "index$": 4 }, { "name": "includeCursor", "required": false, "in": "query", "description": "Include cursor item in response", "schema": { "type": "boolean" }, "index$": 5 }, { "name": "email", "required": false, "in": "query", "description": "Email address of the subscriber to filter results.", "schema": { "type": "string" }, "index$": 6 }, { "name": "name", "required": false, "in": "query", "description": "Name of the subscriber to filter results.", "schema": { "type": "string" }, "index$": 7 }, { "name": "phone", "required": false, "in": "query", "description": "Phone number of the subscriber to filter results.", "schema": { "type": "string" }, "index$": 8 }, { "name": "subscriberId", "required": false, "in": "query", "description": "Unique identifier of the subscriber to filter results.", "schema": { "type": "string" }, "index$": 9 }, { "name": "idempotency-key", "in": "header", "description": "A header for idempotency purposes", "required": false, "schema": { "type": "string" }, "index$": 10 }] } });
        }
        const client = setup.client;
        const struct = setup.struct;
        const isempty = struct.isempty;
        const select = struct.select;
        let list_subscribers_response_dto_ref01_data = Object.values(setup.data.existing.list_subscribers_response_dto)[0];
        // LIST
        const list_subscribers_response_dto_ref01_ent = client.ListSubscribersResponseDto();
        const list_subscribers_response_dto_ref01_match = {};
        const list_subscribers_response_dto_ref01_list = (await list_subscribers_response_dto_ref01_ent.list(list_subscribers_response_dto_ref01_match)).map((e) => e.data());
    });
});
function basicSetup(extra) {
    // TODO: fix test def options
    const options = {}; // null
    // TODO: needs test utility to resolve path
    const entityDataFile = node_path_1.default.resolve(__dirname, '../../../../.sdk/test/entity/list_subscribers_response_dto/ListSubscribersResponseDtoTestData.json');
    // TODO: file ready util needed?
    const entityDataSource = Fs.readFileSync(entityDataFile).toString('utf8');
    // TODO: need a xlang JSON parse utility in voxgig/struct with better error msgs
    const entityData = JSON.parse(entityDataSource);
    options.entity = entityData.existing;
    let client = __1.NovuSDK.test(options, extra);
    const struct = client.utility().struct;
    const merge = struct.merge;
    const transform = struct.transform;
    let idmap = transform(['list_subscribers_response_dto01', 'list_subscribers_response_dto02', 'list_subscribers_response_dto03'], {
        '`$PACK`': ['', {
                '`$KEY`': '`$COPY`',
                '`$VAL`': ['`$FORMAT`', 'upper', '`$COPY`']
            }]
    });
    const env = (0, utility_1.envOverride)({
        'NOVU_TEST_LIST_SUBSCRIBERS_RESPONSE_DTO_ENTID': idmap,
        'NOVU_TEST_LIVE': 'FALSE',
        'NOVU_TEST_EXPLAIN': 'FALSE',
        'NOVU_APIKEY': '',
    });
    idmap = env['NOVU_TEST_LIST_SUBSCRIBERS_RESPONSE_DTO_ENTID'];
    const live = 'TRUE' === env.NOVU_TEST_LIVE;
    const transport = (0, live_runner_1.createLiveTransport)();
    if (live) {
        const rawIds = process.env['NOVU_TEST_LIST_SUBSCRIBERS_RESPONSE_DTO_ENTID'];
        idmap = rawIds && rawIds.trim() ? JSON.parse(rawIds) : {};
        if (!idmap || Array.isArray(idmap) || typeof idmap !== 'object') {
            throw new Error('Live ENTID must be a JSON object');
        }
        client = new __1.NovuSDK(merge([
            // FIRST, so the generated fields below win: sdk-test-control.json's
            // test.client.options adds to the live client, it does not redirect it.
            (0, utility_1.liveClientOptions)(),
            {
                apikey: env.NOVU_APIKEY,
            },
            // 'extra || {}', not a bare 'extra': struct.merge returns UNDEFINED when the
            // last entry is undefined, and basicSetup is normally called with no
            // argument at all - so a bare 'extra' silently discarded the apikey
            // and server values above and handed the SDK undefined. Harmless
            // while there was nothing in that object; not harmless now.
            extra || {},
            { system: { fetch: transport.fetch } }
        ]));
    }
    const setup = {
        idmap,
        env,
        options,
        client,
        struct,
        data: entityData,
        explain: 'TRUE' === env.NOVU_TEST_EXPLAIN,
        live,
        transport,
        now: Date.now(),
    };
    return setup;
}
//# sourceMappingURL=ListSubscribersResponseDtoEntity.test.js.map