// Command Novu-cli is a CLI + REPL for the Novu SDK,
// built on the boru engine. Positional arguments are joined into a
// single boru expression and evaluated; with no arguments, falls into
// a REPL. Generated by sdkgen go-cli target.
package main

import (
	"bufio"
	"fmt"
	"io"
	"os"
	"strings"

	eng "github.com/boru-lang/boru/eng/go"
	"github.com/boru-lang/boru/eng/go/parser"
	sdk "github.com/voxgig-sdk/novu-sdk/go"
)

// prompt is the REPL prompt prefix (matches the SDK slug).
const prompt = "novu"

// entitiesHelp is the space-separated entity list shown by /help.
const entitiesHelp = "activity_notification_response_dto agent agent_integration_response_dto agent_response_dto bulk channel_connection channel_endpoint configure context create_subscriptions_response_dto diff domain domain_connect_apply_url_response_dto domain_connect_status_response_dto domain_response_dto domain_route_response_dto environment environment_tags_dto environment_variable environment_variable_workflow_info_dto event generate_chat_o_auth_url_response_dto generate_preview_response_dto import_master_json_response_dto inbox_notification_dto integration integration_response_dto layout layout_response_dto link list_agent_integrations_response_dto list_agents_response_dto list_channel_connections_response_dto list_channel_endpoints_response_dto list_contexts_response_dto list_domain_routes_response_dto list_domains_response_dto list_subscribers_response_dto list_topic_subscriptions_response_dto list_topics_response_dto master_json message message_response_dto notification_feed_item_dto preferences_response_dto publish remove_subscriber_response_dto step subscriber subscriber_notifications_count_response_dto subscriber_notifications_response_dto subscriber_preferences_dto subscriber_response_dto subscription topic topic_subscriber_dto topic_subscriptions_response_dto translation translation_group_dto trigger trigger_event_response_dto unseen upload webhook_result_dto workflow workflow_info_dto workflow_response_dto"

func main() {
	os.Exit(run(os.Args[1:], os.Stdin, os.Stdout, os.Stderr))
}

// usage prints the CLI help (for --help / -h). No client or network setup.
func usage(out io.Writer) {
	fmt.Fprintf(out, "%s-cli — boru-driven CLI + REPL for the %s SDK\n\n", prompt, prompt)
	fmt.Fprintln(out, "Usage:")
	fmt.Fprintf(out, "  %s-cli [--help] [<boru expression>]\n\n", prompt)
	fmt.Fprintln(out, "With arguments, they are joined into a single boru expression and")
	fmt.Fprintln(out, "evaluated against the API. With no arguments, starts an interactive REPL.")
	fmt.Fprintln(out)
	fmt.Fprintln(out, "Words:    list / load / update <query?> <entity>")
	fmt.Fprintln(out, "Entities:", entitiesHelp)
	fmt.Fprintln(out, "Env:      NOVU_APIKEY (api key), NOVU_BASE (base url override)")
	fmt.Fprintln(out, "REPL:     /help  /quit")
}

func run(args []string, in io.Reader, out, errOut io.Writer) int {
	// --help / -h: print usage and exit before any config or network setup.
	for _, a := range args {
		if a == "--help" || a == "-h" {
			usage(out)
			return 0
		}
	}

	// Configure from the environment: NOVU_APIKEY carries the API key and
	// NOVU_BASE optionally overrides the API base URL (e.g. production).
	// Both injectable by a secrets vault. Unset -> nil config defaults.
	var opts map[string]any
	if apikey := os.Getenv("NOVU_APIKEY"); apikey != "" {
		opts = map[string]any{"apikey": apikey}
	}
	if base := os.Getenv("NOVU_BASE"); base != "" {
		if opts == nil {
			opts = map[string]any{}
		}
		opts["base"] = base
	}
	client := sdk.NewNovuSDK(opts)

	r, err := eng.NewRegistry()
	if err != nil {
		fmt.Fprintf(errOut, "registry: %v\n", err)
		return 1
	}
	registerSDKWords(r, client)
	if err := r.Err(); err != nil {
		fmt.Fprintf(errOut, "word registration: %v\n", err)
		return 1
	}
	r.SetParseFunc(parser.Parse)
	r.InitRootContext()
	r.MarkReady()

	if len(args) > 0 {
		return evalOnce(r, strings.Join(args, " "), out, errOut)
	}
	repl(r, in, out)
	return 0
}

func evalOnce(r *eng.Registry, src string, out, errOut io.Writer) int {
	values, err := parser.Parse(src)
	if err != nil {
		fmt.Fprintf(errOut, "parse: %v\n", err)
		return 1
	}
	result, err := eng.NewTop(r).Run(values)
	if err != nil {
		fmt.Fprintf(errOut, "error: %v\n", err)
		return 1
	}
	for _, v := range result {
		fmt.Fprintln(out, v.String())
	}
	return 0
}

func repl(r *eng.Registry, in io.Reader, out io.Writer) {
	scanner := bufio.NewScanner(in)
	scanner.Buffer(make([]byte, 0, 64*1024), 1024*1024)
	for {
		fmt.Fprintf(out, "%s> ", prompt)
		if !scanner.Scan() {
			fmt.Fprintln(out)
			return
		}
		line := strings.TrimSpace(scanner.Text())
		if line == "" {
			continue
		}
		switch line {
		case "/quit", "/q", "/exit":
			return
		case "/help", "/h", "/?":
			fmt.Fprintln(out, "words:    list / load / update <query?> <entity>")
			fmt.Fprintln(out, "entities:", entitiesHelp)
			fmt.Fprintln(out, "meta:     /help  /quit")
			continue
		}
		values, err := parser.Parse(line)
		if err != nil {
			fmt.Fprintf(out, "  parse error: %v\n", err)
			continue
		}
		result, err := eng.NewTop(r).Run(values)
		if err != nil {
			fmt.Fprintf(out, "  error: %v\n", err)
			continue
		}
		for _, v := range result {
			fmt.Fprintln(out, v.String())
		}
	}
}
