// Generated by sdkgen go-cli target.
package main

import (
	"fmt"
	"strings"

	eng "github.com/boru-lang/boru/eng/go"
	sdk "github.com/voxgig-sdk/novu-sdk/go"
)

func registerSDKWords(r *eng.Registry, client *sdk.NovuSDK) {
	for _, op := range []string{"list", "load", "update"} {
		op := op
		single := eng.Signature{
			Args:      []*eng.Type{eng.TAtom},
			QuoteArgs: map[int]bool{0: true},
			Impl: eng.Go(func(args []eng.Value, _ map[string]eng.Value, _ []eng.Value, _ *eng.Registry) ([]eng.Value, error) {
				return runOp(client, op, nil, args[0])
			}),
			Returns:    []*eng.Type{eng.TAny},
			BarrierPos: eng.BarrierAllForward,
		}
		dual := eng.Signature{
			Args:      []*eng.Type{eng.TAny, eng.TAtom},
			QuoteArgs: map[int]bool{1: true},
			Impl: eng.Go(func(args []eng.Value, _ map[string]eng.Value, _ []eng.Value, _ *eng.Registry) ([]eng.Value, error) {
				q := args[0]
				return runOp(client, op, &q, args[1])
			}),
			Returns:    []*eng.Type{eng.TAny},
			BarrierPos: eng.BarrierAllForward,
		}
		r.RegisterNativeFunc(eng.NativeFunc{
			Name:       op,
			Signatures: []eng.Signature{single, dual},
		})
	}
}

func runOp(client *sdk.NovuSDK, op string, query *eng.Value, entityAtom eng.Value) ([]eng.Value, error) {
	entityName, err := eng.AsAtom(entityAtom)
	if err != nil {
		return nil, fmt.Errorf("%s: entity argument is not an atom: %w", op, err)
	}
	ent, err := entityFor(client, entityName)
	if err != nil {
		return nil, fmt.Errorf("%s: %w", op, err)
	}

	var arg map[string]any
	if query != nil {
		arg, err = queryToMap(*query)
		if err != nil {
			return nil, fmt.Errorf("%s: %w", op, err)
		}
	}

	var result any
	switch op {
	case "list":
		result, err = ent.List(arg, nil)
	case "load":
		result, err = ent.Load(arg, nil)
	case "update":
		result, err = ent.Update(arg, nil)
	default:
		return nil, fmt.Errorf("unknown op %q", op)
	}
	if err != nil {
		return nil, err
	}
	return []eng.Value{eng.FromNative(extractData(result))}, nil
}

// entityFor dispatches on the lowercase entity name. The generator
// emits one `case "<name>":` per entity defined in the SDK model.
func entityFor(client *sdk.NovuSDK, name string) (sdk.NovuEntity, error) {
	switch strings.ToLower(name) {
	case "activity_notification_response_dto":
		return client.ActivityNotificationResponseDto(nil), nil
	case "agent":
		return client.Agent(nil), nil
	case "agent_integration_response_dto":
		return client.AgentIntegrationResponseDto(nil), nil
	case "agent_response_dto":
		return client.AgentResponseDto(nil), nil
	case "bulk":
		return client.Bulk(nil), nil
	case "channel_connection":
		return client.ChannelConnection(nil), nil
	case "channel_endpoint":
		return client.ChannelEndpoint(nil), nil
	case "configure":
		return client.Configure(nil), nil
	case "context":
		return client.Context(nil), nil
	case "create_subscriptions_response_dto":
		return client.CreateSubscriptionsResponseDto(nil), nil
	case "diff":
		return client.Diff(nil), nil
	case "domain":
		return client.Domain(nil), nil
	case "domain_connect_apply_url_response_dto":
		return client.DomainConnectApplyUrlResponseDto(nil), nil
	case "domain_connect_status_response_dto":
		return client.DomainConnectStatusResponseDto(nil), nil
	case "domain_response_dto":
		return client.DomainResponseDto(nil), nil
	case "domain_route_response_dto":
		return client.DomainRouteResponseDto(nil), nil
	case "environment":
		return client.Environment(nil), nil
	case "environment_tags_dto":
		return client.EnvironmentTagsDto(nil), nil
	case "environment_variable":
		return client.EnvironmentVariable(nil), nil
	case "environment_variable_workflow_info_dto":
		return client.EnvironmentVariableWorkflowInfoDto(nil), nil
	case "event":
		return client.Event(nil), nil
	case "generate_chat_o_auth_url_response_dto":
		return client.GenerateChatOAuthUrlResponseDto(nil), nil
	case "generate_preview_response_dto":
		return client.GeneratePreviewResponseDto(nil), nil
	case "import_master_json_response_dto":
		return client.ImportMasterJsonResponseDto(nil), nil
	case "inbox_notification_dto":
		return client.InboxNotificationDto(nil), nil
	case "integration":
		return client.Integration(nil), nil
	case "integration_response_dto":
		return client.IntegrationResponseDto(nil), nil
	case "layout":
		return client.Layout(nil), nil
	case "layout_response_dto":
		return client.LayoutResponseDto(nil), nil
	case "link":
		return client.Link(nil), nil
	case "list_agent_integrations_response_dto":
		return client.ListAgentIntegrationsResponseDto(nil), nil
	case "list_domain_routes_response_dto":
		return client.ListDomainRoutesResponseDto(nil), nil
	case "list_topic_subscriptions_response_dto":
		return client.ListTopicSubscriptionsResponseDto(nil), nil
	case "master_json":
		return client.MasterJson(nil), nil
	case "message":
		return client.Message(nil), nil
	case "message_response_dto":
		return client.MessageResponseDto(nil), nil
	case "notification_feed_item_dto":
		return client.NotificationFeedItemDto(nil), nil
	case "preferences_response_dto":
		return client.PreferencesResponseDto(nil), nil
	case "publish":
		return client.Publish(nil), nil
	case "remove_subscriber_response_dto":
		return client.RemoveSubscriberResponseDto(nil), nil
	case "step":
		return client.Step(nil), nil
	case "subscriber":
		return client.Subscriber(nil), nil
	case "subscriber_notifications_count_response_dto":
		return client.SubscriberNotificationsCountResponseDto(nil), nil
	case "subscriber_notifications_response_dto":
		return client.SubscriberNotificationsResponseDto(nil), nil
	case "subscriber_preferences_dto":
		return client.SubscriberPreferencesDto(nil), nil
	case "subscriber_response_dto":
		return client.SubscriberResponseDto(nil), nil
	case "subscription":
		return client.Subscription(nil), nil
	case "topic":
		return client.Topic(nil), nil
	case "topic_subscriber_dto":
		return client.TopicSubscriberDto(nil), nil
	case "topic_subscriptions_response_dto":
		return client.TopicSubscriptionsResponseDto(nil), nil
	case "translation":
		return client.Translation(nil), nil
	case "translation_group_dto":
		return client.TranslationGroupDto(nil), nil
	case "trigger_event_response_dto":
		return client.TriggerEventResponseDto(nil), nil
	case "unseen":
		return client.Unseen(nil), nil
	case "upload":
		return client.Upload(nil), nil
	case "webhook_result_dto":
		return client.WebhookResultDto(nil), nil
	case "workflow":
		return client.Workflow(nil), nil
	case "workflow_info_dto":
		return client.WorkflowInfoDto(nil), nil
	case "workflow_response_dto":
		return client.WorkflowResponseDto(nil), nil

	}
	return nil, fmt.Errorf("unknown entity %q", name)
}

// queryToMap converts a boru Value (Map or Scalar) into the
// `map[string]any` shape the SDK expects. Maps are unwrapped via
// eng.ToNative. Scalars are wrapped as {"id": <value>} so the
// shorthand `load 1 book` becomes `load {id:1} book`.
func queryToMap(v eng.Value) (map[string]any, error) {
	if v.Parent.ConformsTo(eng.TMap) {
		m, ok := eng.ToNative(v).(map[string]any)
		if !ok {
			return nil, fmt.Errorf("query map could not be unwrapped")
		}
		return m, nil
	}
	if v.Parent.ConformsTo(eng.TScalar) {
		return map[string]any{"id": eng.ToNative(v)}, nil
	}
	return nil, fmt.Errorf("query must be a Map or Scalar, got %s", v.Parent)
}

// extractData walks an SDK result and replaces any sdk.Entity wrapper
// with the underlying record via .Data().
func extractData(x any) any {
	switch v := x.(type) {
	case sdk.Entity:
		return extractData(v.Data())
	case []any:
		out := make([]any, len(v))
		for i, e := range v {
			out[i] = extractData(e)
		}
		return out
	case map[string]any:
		out := make(map[string]any, len(v))
		for k, vv := range v {
			out[k] = extractData(vv)
		}
		return out
	}
	return x
}
