"use strict";
var __createBinding = (this && this.__createBinding) || (Object.create ? (function(o, m, k, k2) {
    if (k2 === undefined) k2 = k;
    var desc = Object.getOwnPropertyDescriptor(m, k);
    if (!desc || ("get" in desc ? !m.__esModule : desc.writable || desc.configurable)) {
      desc = { enumerable: true, get: function() { return m[k]; } };
    }
    Object.defineProperty(o, k2, desc);
}) : (function(o, m, k, k2) {
    if (k2 === undefined) k2 = k;
    o[k2] = m[k];
}));
var __setModuleDefault = (this && this.__setModuleDefault) || (Object.create ? (function(o, v) {
    Object.defineProperty(o, "default", { enumerable: true, value: v });
}) : function(o, v) {
    o["default"] = v;
});
var __importStar = (this && this.__importStar) || (function () {
    var ownKeys = function(o) {
        ownKeys = Object.getOwnPropertyNames || function (o) {
            var ar = [];
            for (var k in o) if (Object.prototype.hasOwnProperty.call(o, k)) ar[ar.length] = k;
            return ar;
        };
        return ownKeys(o);
    };
    return function (mod) {
        if (mod && mod.__esModule) return mod;
        var result = {};
        if (mod != null) for (var k = ownKeys(mod), i = 0; i < k.length; i++) if (k[i] !== "default") __createBinding(result, mod, k[i]);
        __setModuleDefault(result, mod);
        return result;
    };
})();
var __importDefault = (this && this.__importDefault) || function (mod) {
    return (mod && mod.__esModule) ? mod : { "default": mod };
};
Object.defineProperty(exports, "__esModule", { value: true });
const node_path_1 = __importDefault(require("node:path"));
const Fs = __importStar(require("node:fs"));
const node_test_1 = require("node:test");
const node_assert_1 = __importDefault(require("node:assert"));
const live_runner_1 = require("../../live-runner");
const live_entity_1 = require("../../live-entity");
const __1 = require("../../..");
const utility_1 = require("../../utility");
(0, utility_1.loadEnvLocal)(__dirname + '/../../../.env.local');
(0, node_test_1.describe)('SubscriberResponseDtoEntity', async () => {
    // Per-test live pacing. Delay is read from sdk-test-control.json's
    // `test.live.delayMs`; only sleeps when NOVU_TEST_LIVE=TRUE.
    (0, node_test_1.afterEach)((0, utility_1.liveDelay)('NOVU_TEST_LIVE'));
    (0, node_test_1.test)('instance', async () => {
        const testsdk = __1.NovuSDK.test();
        const ent = testsdk.SubscriberResponseDto();
        (0, node_assert_1.default)(null != ent);
    });
    (0, node_test_1.test)('basic', async (t) => {
        const live = 'TRUE' === process.env.NOVU_TEST_LIVE;
        for (const op of ['update']) {
            if (!live && (0, utility_1.maybeSkipControl)(t, 'entityOp', 'subscriber_response_dto.' + op, live))
                return;
        }
        const setup = basicSetup();
        if (setup.live) {
            return (0, live_entity_1.runLiveEntity)(setup, { "active": true, "alias": { "field": {} }, "fields": { "avatar": { "a": true, "h": "Avatar", "n": "avatar", "r": false, "sh": "The URL of the subscriber's avatar image.", "t": "`$STRING`", "key$": "avatar", "index$": 0 }, "channels": { "a": true, "h": "Channels", "n": "channels", "r": false, "sh": "An array of channel settings associated with the subscriber.", "t": "`$ARRAY`", "key$": "channels", "index$": 1 }, "createdAt": { "a": true, "h": "Created At", "n": "createdAt", "r": true, "sh": "The timestamp indicating when the subscriber was created, in ISO 8601 format.", "t": "`$STRING`", "key$": "createdAt", "index$": 2 }, "data": { "a": true, "h": "Data", "n": "data", "r": false, "sh": "Additional custom data for the subscriber", "t": "`$OBJECT`", "key$": "data", "index$": 3 }, "deleted": { "a": true, "h": "Deleted", "n": "deleted", "r": true, "sh": "Indicates whether the subscriber has been deleted.", "t": "`$BOOLEAN`", "key$": "deleted", "index$": 4 }, "email": { "a": true, "h": "Email", "n": "email", "r": false, "sh": "The email address of the subscriber.", "t": "`$STRING`", "key$": "email", "index$": 5 }, "environmentId": { "a": true, "h": "Environment Id", "n": "environmentId", "r": true, "sh": "The unique identifier of the environment associated with this subscriber.", "t": "`$STRING`", "key$": "environmentId", "index$": 6 }, "firstName": { "a": true, "h": "First Name", "n": "firstName", "r": false, "sh": "The first name of the subscriber.", "t": "`$STRING`", "key$": "firstName", "index$": 7 }, "id": { "a": true, "h": "Id", "n": "id", "r": false, "sh": "The internal ID generated by Novu for your subscriber.", "t": "`$STRING`", "key$": "id", "index$": 8 }, "isOnline": { "a": true, "h": "Is Online", "n": "isOnline", "r": false, "sh": "Indicates whether the subscriber is currently online.", "t": "`$BOOLEAN`", "key$": "isOnline", "index$": 9 }, "lastName": { "a": true, "h": "Last Name", "n": "lastName", "r": false, "sh": "The last name of the subscriber.", "t": "`$STRING`", "key$": "lastName", "index$": 10 }, "lastOnlineAt": { "a": true, "h": "Last Online At", "n": "lastOnlineAt", "r": false, "sh": "The timestamp indicating when the subscriber was last online, in ISO 8601 format.", "t": "`$STRING`", "key$": "lastOnlineAt", "index$": 11 }, "locale": { "a": true, "h": "Locale", "n": "locale", "r": false, "sh": "The locale setting of the subscriber, indicating their preferred language or region.", "t": "`$STRING`", "key$": "locale", "index$": 12 }, "organizationId": { "a": true, "h": "Organization Id", "n": "organizationId", "r": true, "sh": "The unique identifier of the organization to which the subscriber belongs.", "t": "`$STRING`", "key$": "organizationId", "index$": 13 }, "phone": { "a": true, "h": "Phone", "n": "phone", "r": false, "sh": "The phone number of the subscriber.", "t": "`$STRING`", "key$": "phone", "index$": 14 }, "subscriberId": { "a": true, "h": "Subscriber Id", "n": "subscriberId", "r": true, "sh": "The identifier used to create this subscriber, which typically corresponds to the user ID in your system.", "t": "`$STRING`", "key$": "subscriberId", "index$": 15 }, "timezone": { "a": true, "h": "Timezone", "n": "timezone", "r": false, "sh": "Timezone of the subscriber", "t": "`$STRING`", "key$": "timezone", "index$": 16 }, "topics": { "a": true, "de": true, "h": "Topics", "n": "topics", "r": false, "sh": "An array of topics that the subscriber is subscribed to.", "t": "`$ARRAY`", "key$": "topics", "index$": 17 }, "updatedAt": { "a": true, "h": "Updated At", "n": "updatedAt", "r": true, "sh": "The timestamp indicating when the subscriber was last updated, in ISO 8601 format.", "t": "`$STRING`", "key$": "updatedAt", "index$": 18 }, "v": { "a": true, "h": "V", "n": "v", "r": false, "sh": "The version of the subscriber document.", "t": "`$NUMBER`", "key$": "v", "index$": 19 } }, "id": { "field": "id", "name": "id" }, "name": "subscriber_response_dto", "op": { "update": { "input": "data", "name": "update", "points": [{ "a": true, "co": { "id": "PATCH /v1/subscribers/{subscriberId}/credentials", "source": "openapi3", "version": 2 }, "g": { "header": [{ "a": true, "k": "header", "n": "idempotency_key", "or": "idempotency_key", "r": false, "t": "`$STRING`", "index$": 0 }], "params": [{ "a": true, "k": "param", "n": "id", "or": "subscriber_id", "r": true, "t": "`$STRING`", "index$": 0 }] }, "k": "http", "m": "PATCH", "o": "/v1/subscribers/{subscriberId}/credentials", "q": { "$action": "credentials", "exist": ["id", "idempotency_key"] }, "r": { "param": { "subscriberId": "id" } }, "s": [{ "lit": "v1" }, { "lit": "subscribers" }, { "var": "id" }, { "lit": "credentials" }], "t": { "req": "`reqdata`", "res": "`body`" }, "index$": 0 }, { "a": true, "co": { "id": "PUT /v1/subscribers/{subscriberId}/credentials", "source": "openapi3", "version": 2 }, "g": { "header": [{ "a": true, "k": "header", "n": "idempotency_key", "or": "idempotency_key", "r": false, "t": "`$STRING`", "index$": 0 }], "params": [{ "a": true, "k": "param", "n": "id", "or": "subscriber_id", "r": true, "t": "`$STRING`", "index$": 0 }] }, "k": "http", "m": "PUT", "o": "/v1/subscribers/{subscriberId}/credentials", "q": { "$action": "credentials", "exist": ["id", "idempotency_key"] }, "r": { "param": { "subscriberId": "id" } }, "s": [{ "lit": "v1" }, { "lit": "subscribers" }, { "var": "id" }, { "lit": "credentials" }], "t": { "req": "`reqdata`", "res": "`body`" }, "index$": 1 }, { "a": true, "co": { "id": "PATCH /v1/subscribers/{subscriberId}/online-status", "source": "openapi3", "version": 2 }, "g": { "header": [{ "a": true, "k": "header", "n": "idempotency_key", "or": "idempotency_key", "r": false, "t": "`$STRING`", "index$": 0 }], "params": [{ "a": true, "k": "param", "n": "id", "or": "subscriber_id", "r": true, "t": "`$STRING`", "index$": 0 }] }, "k": "http", "m": "PATCH", "o": "/v1/subscribers/{subscriberId}/online-status", "q": { "$action": "online-status", "exist": ["id", "idempotency_key"] }, "r": { "param": { "subscriberId": "id" } }, "s": [{ "lit": "v1" }, { "lit": "subscribers" }, { "var": "id" }, { "lit": "online-status" }], "t": { "req": "`reqdata`", "res": "`body`" }, "index$": 2 }], "key$": "update" } }, "relations": { "ancestors": [] }, "key$": "subscriber_response_dto", "name__orig": "subscriber_response_dto", "Name": "SubscriberResponseDto", "name_": "subscriber_response_dto", "name-": "subscriber-response-dto", "NAME": "SUBSCRIBER_RESPONSE_DTO", "index$": 52 }, { "active": true, "entity": "subscriber_response_dto", "key$": "BasicSubscriberResponseDtoFlow", "kind": "basic", "name": "BasicSubscriberResponseDtoFlow", "param": {}, "step": [{ "a": true, "d": {}, "i": { "ref": "subscriber_response_dto_ref01", "srcdatavar": "subscriber_response_dto_ref01_data", "suffix": "_up0", "textfield": "avatar" }, "m": {}, "o": "update", "s": [{ "apply": "TextFieldMark", "def": { "mark": "Mark01-subscriber_response_dto_ref01" } }], "v": [], "index$": 0 }] }, 'SubscriberResponseDto', { "PATCH /v1/subscribers/{subscriberId}/credentials": { "protocol": "http", "requestBody": { "required": true, "content": { "application/json": { "schema": { "type": "object", "properties": { "providerId": { "type": "string", "description": "The provider identifier for the credentials", "enum": ["slack", "discord", "google-chat", "msteams", "webex-messaging", "mattermost", "ryver", "zulip", "grafana-on-call", "getstream", "rocket-chat", "whatsapp-business", "line", "chat-webhook", "novu-slack", "telegram", "sendblue", "photon-imessage", "novu-web-chat", "fcm", "apns", "expo", "one-signal", "pushpad", "push-webhook", "pusher-beams", "appio"], "x-ref": "#/components/schemas/ChatOrPushProviderEnum" }, "integrationIdentifier": { "type": "string", "description": "The integration identifier" }, "credentials": { "description": "Credentials payload for the specified provider", "allOf": [{ "type": "object", "properties": { "webhookUrl": {}, "channel": {}, "deviceTokens": {}, "alertUid": {}, "title": {}, "imageUrl": {}, "state": {}, "externalUrl": {} }, "x-ref": "#/components/schemas/ChannelCredentials" }] } }, "required": ["providerId", "credentials"], "x-ref": "#/components/schemas/UpdateSubscriberChannelRequestDto" } } } }, "parameters": [{ "name": "subscriberId", "required": true, "in": "path", "schema": { "type": "string" }, "index$": 0 }, { "name": "idempotency-key", "in": "header", "description": "A header for idempotency purposes", "required": false, "schema": { "type": "string" }, "index$": 1 }] }, "PUT /v1/subscribers/{subscriberId}/credentials": { "protocol": "http", "requestBody": { "required": true, "content": { "application/json": { "schema": { "type": "object", "properties": { "providerId": { "type": "string", "description": "The provider identifier for the credentials", "enum": ["slack", "discord", "google-chat", "msteams", "webex-messaging", "mattermost", "ryver", "zulip", "grafana-on-call", "getstream", "rocket-chat", "whatsapp-business", "line", "chat-webhook", "novu-slack", "telegram", "sendblue", "photon-imessage", "novu-web-chat", "fcm", "apns", "expo", "one-signal", "pushpad", "push-webhook", "pusher-beams", "appio"], "x-ref": "#/components/schemas/ChatOrPushProviderEnum" }, "integrationIdentifier": { "type": "string", "description": "The integration identifier" }, "credentials": { "description": "Credentials payload for the specified provider", "allOf": [{ "type": "object", "properties": { "webhookUrl": {}, "channel": {}, "deviceTokens": {}, "alertUid": {}, "title": {}, "imageUrl": {}, "state": {}, "externalUrl": {} }, "x-ref": "#/components/schemas/ChannelCredentials" }] } }, "required": ["providerId", "credentials"], "x-ref": "#/components/schemas/UpdateSubscriberChannelRequestDto" } } } }, "parameters": [{ "name": "subscriberId", "required": true, "in": "path", "schema": { "type": "string" }, "index$": 0 }, { "name": "idempotency-key", "in": "header", "description": "A header for idempotency purposes", "required": false, "schema": { "type": "string" }, "index$": 1 }] }, "PATCH /v1/subscribers/{subscriberId}/online-status": { "protocol": "http", "requestBody": { "required": true, "content": { "application/json": { "schema": { "type": "object", "properties": { "isOnline": { "type": "boolean" } }, "required": ["isOnline"], "x-ref": "#/components/schemas/UpdateSubscriberOnlineFlagRequestDto" } } } }, "parameters": [{ "name": "subscriberId", "required": true, "in": "path", "schema": { "type": "string" }, "index$": 0 }, { "name": "idempotency-key", "in": "header", "description": "A header for idempotency purposes", "required": false, "schema": { "type": "string" }, "index$": 1 }] } });
        }
        const client = setup.client;
        const struct = setup.struct;
        const isempty = struct.isempty;
        const select = struct.select;
        let subscriber_response_dto_ref01_data = Object.values(setup.data.existing.subscriber_response_dto)[0];
        // UPDATE
        const subscriber_response_dto_ref01_ent = client.SubscriberResponseDto();
        const subscriber_response_dto_ref01_data_up0 = {};
        subscriber_response_dto_ref01_data_up0.id = subscriber_response_dto_ref01_data.id;
        const subscriber_response_dto_ref01_markdef_up0 = { name: 'avatar', value: 'Mark01-subscriber_response_dto_ref01_' + setup.now };
        subscriber_response_dto_ref01_data_up0[subscriber_response_dto_ref01_markdef_up0.name] = subscriber_response_dto_ref01_markdef_up0.value;
        const subscriber_response_dto_ref01_resdata_up0 = (await subscriber_response_dto_ref01_ent.update(subscriber_response_dto_ref01_data_up0)).data();
        (0, node_assert_1.default)(subscriber_response_dto_ref01_resdata_up0.id === subscriber_response_dto_ref01_data_up0.id);
        (0, node_assert_1.default)(subscriber_response_dto_ref01_resdata_up0[subscriber_response_dto_ref01_markdef_up0.name] === subscriber_response_dto_ref01_markdef_up0.value);
    });
});
function basicSetup(extra) {
    // TODO: fix test def options
    const options = {}; // null
    // TODO: needs test utility to resolve path
    const entityDataFile = node_path_1.default.resolve(__dirname, '../../../../.sdk/test/entity/subscriber_response_dto/SubscriberResponseDtoTestData.json');
    // TODO: file ready util needed?
    const entityDataSource = Fs.readFileSync(entityDataFile).toString('utf8');
    // TODO: need a xlang JSON parse utility in voxgig/struct with better error msgs
    const entityData = JSON.parse(entityDataSource);
    options.entity = entityData.existing;
    let client = __1.NovuSDK.test(options, extra);
    const struct = client.utility().struct;
    const merge = struct.merge;
    const transform = struct.transform;
    let idmap = transform(['subscriber_response_dto01', 'subscriber_response_dto02', 'subscriber_response_dto03'], {
        '`$PACK`': ['', {
                '`$KEY`': '`$COPY`',
                '`$VAL`': ['`$FORMAT`', 'upper', '`$COPY`']
            }]
    });
    const env = (0, utility_1.envOverride)({
        'NOVU_TEST_SUBSCRIBER_RESPONSE_DTO_ENTID': idmap,
        'NOVU_TEST_LIVE': 'FALSE',
        'NOVU_TEST_EXPLAIN': 'FALSE',
        'NOVU_APIKEY': '',
    });
    idmap = env['NOVU_TEST_SUBSCRIBER_RESPONSE_DTO_ENTID'];
    const live = 'TRUE' === env.NOVU_TEST_LIVE;
    const transport = (0, live_runner_1.createLiveTransport)();
    if (live) {
        const rawIds = process.env['NOVU_TEST_SUBSCRIBER_RESPONSE_DTO_ENTID'];
        idmap = rawIds && rawIds.trim() ? JSON.parse(rawIds) : {};
        if (!idmap || Array.isArray(idmap) || typeof idmap !== 'object') {
            throw new Error('Live ENTID must be a JSON object');
        }
        client = new __1.NovuSDK(merge([
            // FIRST, so the generated fields below win: sdk-test-control.json's
            // test.client.options adds to the live client, it does not redirect it.
            (0, utility_1.liveClientOptions)(),
            {
                apikey: env.NOVU_APIKEY,
            },
            // 'extra || {}', not a bare 'extra': struct.merge returns UNDEFINED when the
            // last entry is undefined, and basicSetup is normally called with no
            // argument at all - so a bare 'extra' silently discarded the apikey
            // and server values above and handed the SDK undefined. Harmless
            // while there was nothing in that object; not harmless now.
            extra || {},
            { system: { fetch: transport.fetch } }
        ]));
    }
    const setup = {
        idmap,
        env,
        options,
        client,
        struct,
        data: entityData,
        explain: 'TRUE' === env.NOVU_TEST_EXPLAIN,
        live,
        transport,
        now: Date.now(),
    };
    return setup;
}
//# sourceMappingURL=SubscriberResponseDtoEntity.test.js.map